sudo: required
os: linux
dist: trusty
language: python
matrix:
    include:
        - python: 3.5
          env: LATEST="false" TENSORFLOW="false" COVERAGE="false" NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.17" SKLEARN_VERSION="0.17" PANDAS_VERSION="0.17.1" MATPLOTLIB_VERSION="1.5.1"
        - python: 3.5
          env: LATEST="true" TENSORFLOW="false" COVERAGE="false"
        - python: 3.4
          env: LATEST="true" TENSORFLOW="false" COVERAGE="false"
        - python: 3.4
          env: LATEST="true" TENSORFLOW="true" COVERAGE="false"
        - python: 2.7
          env: LATEST="true" TENSORFLOW="false" COVERAGE="false"
        - python: 2.7
          env: LATEST="true" TENSORFLOW="true" COVERAGE="false"
install:
    - ci/.travis_install.sh
script:
    - echo "test"
after_success:
    - if [[ "${COVERAGE}" == "true" ]]; then coveralls || echo "failed"; fi
notifications:
    email:
      recipients:
          - mail@sebastianraschka.com
    on_success: always
    on_failure: always
